from magasin import client

liste_CP = [42100, 42270, 42580, 42650, 42350, 42390, 42530, 42660, 42290, 42230]
liste_adrs = [
    "Victor Hugo",
    "Jean-Jaures",
    "Gambeta",
    "Pampidou",
    "Général leclerc",
    "Maréchal Foch",
    "Za Les Montagnes ",
    "YANNICK DEVAUX",
    "XAVIER PRIVAS",
    "WINDSOR",
    "WILLIAM HUNT",
    "WATTEAU",
    "WALDECK ROUSSEAU",
    "VOLTAIRE",
    "VLADIMIR DURKOVIC",
    "VIVARAIZE",
    "VITAL MERLEY",
    "VITAL DESCOS",
    "VISITATION",
    "VIRGINIA WOOLF",
    "VIRGILE",
    "VIOLETTE",
    "VIOLETTE",
    "VINGT NEUF BRUMAIRE",
    "VINCENT D INDY",
    "VILLEBOEUF",
    "VIGNAT",
    "VIGNASSE",
    "VIEUX PUITS DE LA CHANA",
    "VICTORIN DELAUZUN",
    "VICTOR JOURJON",
    "VICTOR HUGO",
    "VICTOR GRIGNARD",
    "VICTOR GOMY",
    "VICTOR DUCHAMP",
    "VICTOR DE LAPRADE",
    "VICTOR DE LAPRADE" "VICTOR BASCH",
    "VIAL",
    "VERCINGETORIX",
    "VELOCIO",
    "VAUCANSON",
    "VALMY",
    "VALETTE",
    "VALENTIN HAUY",
    "VALBENOITE",
    "VAL BOISE",
    "VAILLANT COUTURIER",
    "VACHER",
    "VACHER",
    "URBAIN THEVENON",
    "TROUSSEAU",
    "TREMAS",
    "TREFILERIE",
    "TRAVERSIERE",
    "TOURNEFORT",
    "TOUR PHILIPPE",
    "TOULOUSE LAUTREC",
    "TIVET",
    "TIBLIER VERNE",
    "THOMAS EDISON",
    "THIOLLIERE-MATRAT",
    "THIOLLIERE",
    "THIMONNIER",
    "THIERS",
    "THIBAUDIER PROLONGEE",
    "THIBAUDIER",
    "THEOPHRASTE RENAUDOT",
    "THEOPHILE ROUSSEL",
    "THEODORE DE BANVILLE",
    "THEO DELSART",
    "TEYSSOT",
    "TESTENOIRE LAFAYETTE",
    "TENNIS",
    "TECHNOPOLE",
    "TARENTAIZE",
    "STE CATHERINE",
    "STALINGRAD",
    "ST VINCENT DE PAUL",
    "ST BARTHELEMY",
    "SOVIGNET",
    "SOUVENIR 11 NOVEMBRE 1918",
    "SOUS LT JOSEPH VERGNETTE",
    "SOUS LES GALLIERES",
    "SOUS LE CHEMIN",
    "SOUS LA VIALLE",
    "SOUS LA VIALLE",
    "SOUS LA CHAPELLE",
    "SOLEYSEL",
    "SOLEILHAC",
    "SOLAURE",
    "SOLAURE",
    "SHAKESPEARE",
    "SEVERINE",
    "SERMENT DU JEU DE PAUME",
    "SEONS",
    "SEGUIN",
    "SCHEURER KESTNER",
    "SATURNIN GUICHARD",
    "SALVARIS",
    "SALVADOR DALI",
    "SALVADOR ALLENDE",
    "SAINTE-MARIE",
    "SAINTE MARGUERITE",
]
liste_prenom = [
    "Geneviève",
    "Odilon",
    "Édouard",
    "Mélaine",
    "Raymond",
    "Lucien",
    "Alix",
    "Guillaume",
    "Paulin",
    "Tatiana",
    "Yvette",
    "Nina",
    "Rémi",
    "Marcel",
    "Roseline",
    "Prisca",
    "Marius",
    "Sébastien",
    "Agnès",
    "Vincent",
    "Barnard",
    "François",
    "Ananie",
    "Paule",
    "Angèle",
    "Thomas",
    "Gildas",
    "Martine",
    "Marcelle",
    "Hugues",
    "Sandrine",
    "Alexandrine",
    "Richard",
    "Isidore",
    "Irène",
    "Marcellin",
    "Jean-Baptiste",
    "Julie",
    "Gauthier",
    "Fulbert",
    "Stanislas",
    "Jules",
    "Ida",
    "Maxime",
    "Paterne",
    "Benoît-Joseph",
    "Anicet",
    "Parfait",
    "Emma",
    "Odette",
    "Anselme",
    "Alexandre",
    "Georges",
    "Fidèle",
    "Marc",
    "Alida",
    "Zita",
    "Valérie",
    "Catherine",
    "Robert",
    "Thierry",
    "Martinien",
    "Thomas",
    "Florent",
    "Antoine",
    "Mariette",
    "Raoul",
    "Thibaut",
    "Amandine",
    "Ulrich",
    "Benoît",
    "Olivier",
    "Henri",
    "Joël",
    "Camille",
    "Donald",
    "Carmen",
    "Charlotte",
    "Frédéric",
    "Arsène",
    "Marina",
    "Victor",
    "Marie-Madeleine",
    "Brigitte",
    "Christine",
    "Jacques",
    "Anne",
    "Joachim",
    "Nathalie",
    "Samson",
    "Marthe",
    "Juliette",
    "Ignace",
]
liste_nom = [
    "Martin",
    "Bernard",
    "Thomas",
    "Petit",
    "Robert",
    "Richard",
    "Durand",
    "Dubois",
    "Moreau",
    "Laurent",
    "Simon",
    "Michel",
    "Lefebvre",
    "Leroy",
    "Roux",
    "David",
    "Bertrand",
    "Morel",
    "Fournier",
    "Girard",
    "Bonnet",
    "Dupont",
    "Lambert",
    "Fontaine",
    "Rousseau",
    "Vincent",
    "Muller",
    "Lefevre",
    "Faure",
    "Andre",
    "Mercier",
    "Blanc",
    "Guerin",
    "Boyer",
    "Garnier",
    "Chevalier",
    "Francois",
    "Legrand",
    "Gauthier",
    "Garcia",
    "Perrin",
    "Robin",
    "Clement",
    "Morin",
    "Nicolas",
    "Henry",
    "Roussel",
    "Mathieu",
    "Gautier",
    "Masson",
    "Marchand",
    "Denis",
    "Dumont",
    "Marie",
    "Lemaire",
    "Noel",
    "Meyer",
    "Dufour",
    "Meunier",
    "Brun",
    "Blanchard",
    "Giraud",
    "Joly",
    "Riviere",
    "Lucas",
    "Brunet",
    "Gaillard",
    "Barbier",
    "Arnaud",
    "Martinez",
    "Gerard",
    "Roche",
    "Renard",
    "Schmitt",
    "Roy",
    "Leroux",
    "Colin",
    "Vidal",
    "Caron",
    "Picard",
    "Roger",
    "Fabre",
    "Aubert",
    "Lemoine",
    "Renaud",
    "Dumas",
    "Lacroix",
    "Olivier",
    "Philippe",
    "Bourgeois",
    "Pierre",
    "Benoit",
    "Rey",
    "Leclerc",
    "Payet",
    "Rolland",
    "Leclerc",
    "Guillaume",
    "Lecomte",
]
liste_telephone = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
liste_email_at = [
    "@gmail.com",
    "@outlook.com",
    "@yahoo",
    "@orange.fr",
    "@laposte.fr",
    "@bouygue.fr",
]
liste_age = [
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    68,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
]
sexe = ["M", "F", "F", "M", "F"]
rrv = ["Route", "Voie", "Rue", "impasse", "PL", "ALL", "SQ", "ESPA", "BD", "CD", "CRS"]
